services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
