# Generated by Django 5.0.2 on 2024-03-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Detail',
            fields=[
                ('city', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('location', models.FloatField(max_length=15, unique=True)),
            ],
        ),
    ]
