# Generated by Django 5.0.2 on 2024-03-05 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0002_city_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_from', to='bus_managing.city_detail')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_to', to='bus_managing.city_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Route_Detail',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('cities', models.ManyToManyField(related_name='route_cities', to='bus_managing.city_detail')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='bus_managing.city_detail')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_city', to='bus_managing.city_detail')),
            ],
        ),
    ]
