# Generated by Django 5.0.2 on 2024-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0004_alter_route_detail_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_detail',
            name='cities',
            field=models.ManyToManyField(limit_choices_to={'city__in': ['Rajkot', 'Junagadh']}, related_name='route_cities', to='bus_managing.city_detail'),
        ),
    ]
