# Generated by Django 5.0.2 on 2024-03-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0009_route_detail_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Type',
            fields=[
                ('bus_type', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('fare', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='11:48'),
        ),
        migrations.CreateModel(
            name='Bus_Detail',
            fields=[
                ('bus_name', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('route_id', models.ManyToManyField(related_name='r_id', to='bus_managing.route_detail')),
                ('bus_type', models.ForeignKey(blank=True, max_length=122, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_managing.bus_type')),
            ],
        ),
    ]
