# Generated by Django 5.0.2 on 2024-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0010_bus_type_citiesorder_time_bus_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('seats', models.PositiveIntegerField(max_length=40)),
                ('bus_name', models.CharField(max_length=122)),
                ('total_fare', models.FloatField(max_length=15)),
                ('txn_password', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='11:58'),
        ),
    ]
