# Generated by Django 5.0.2 on 2024-03-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0011_advance_booking_alter_citiesorder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_detail',
            name='location',
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='13:04'),
        ),
    ]
