# Generated by Django 5.0.2 on 2024-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0012_remove_city_detail_location_alter_citiesorder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='13:06'),
        ),
    ]
