# Generated by Django 5.0.2 on 2024-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0014_alter_citiesorder_time_alter_route_detail_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='13:56'),
        ),
        migrations.AlterField(
            model_name='route_detail',
            name='cities',
            field=models.ManyToManyField(limit_choices_to={'city__in': ['Junagadh', 'Rajkot', 'Nadiad']}, related_name='route_cities', through='bus_managing.CitiesOrder', to='bus_managing.city_detail'),
        ),
    ]
