# Generated by Django 5.0.2 on 2024-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0015_alter_citiesorder_time_alter_route_detail_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_detail',
            name='cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus_detail',
            name='seats',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='16:21'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('government_agent', 'Government Agent')], default='Passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='route_detail',
            name='cities',
            field=models.ManyToManyField(limit_choices_to={'city__in': ['Junagadh', 'Rajkot', 'Nadiad', 'Ahmedabad']}, related_name='route_cities', through='bus_managing.CitiesOrder', to='bus_managing.city_detail'),
        ),
    ]
