# Generated by Django 5.0.2 on 2024-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0016_bus_detail_cost_bus_detail_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='id',
        ),
        migrations.AddField(
            model_name='distance',
            name='dis_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='18:58'),
        ),
    ]
