# Generated by Django 5.0.2 on 2024-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0018_remove_bus_detail_route_id_alter_citiesorder_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_detail',
            old_name='route_id',
            new_name='route',
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='07:43'),
        ),
    ]
