# Generated by Django 5.0.2 on 2024-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0019_rename_route_id_bus_detail_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_detail',
            name='cost',
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='11:34'),
        ),
    ]
