# Generated by Django 5.0.2 on 2024-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0020_remove_bus_detail_cost_alter_citiesorder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_detail',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus_detail',
            name='bus_name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='17:01'),
        ),
    ]
