# Generated by Django 5.0.2 on 2024-03-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0021_bus_detail_id_alter_bus_detail_bus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_detail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='17:02'),
        ),
    ]
