# Generated by Django 5.0.2 on 2024-03-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0023_remove_bus_detail_id_alter_bus_detail_bus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_detail',
            name='bus_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus_detail',
            name='bus_name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='17:05'),
        ),
    ]
