# Generated by Django 5.0.2 on 2024-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0026_advance_booking_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_booking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='08:53'),
        ),
    ]
