# Generated by Django 5.0.2 on 2024-04-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0027_advance_booking_phone_alter_citiesorder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_seats',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='10:52'),
        ),
    ]
