# Generated by Django 5.0.2 on 2024-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0028_bus_seats_available_alter_citiesorder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_detail',
            name='date',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus_seats',
            name='date',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='16:47'),
        ),
    ]
