# Generated by Django 5.0.2 on 2024-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0029_bus_detail_date_bus_seats_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_booking',
            name='doj',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='17:00'),
        ),
    ]
