# Generated by Django 5.0.2 on 2024-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_managing', '0031_bus_detail_available_seats_alter_citiesorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_detail',
            name='available_seats',
            field=models.IntegerField(default=models.IntegerField(max_length=50), max_length=50),
        ),
        migrations.AlterField(
            model_name='citiesorder',
            name='time',
            field=models.TimeField(default='04:29'),
        ),
    ]
