# Generated by Django 5.2.4 on 2025-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managing", "0032_alter_bus_detail_available_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_detail",
            name="available_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bus_detail",
            name="seats",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="citiesorder",
            name="time",
            field=models.TimeField(default="06:29"),
        ),
    ]
